# The Docker image that will be used to build your app
image: node:latest
# Functions that should be executed before the build script is run
before_script:
  - echo began at $(date)
pages:
  script:
    - echo -e "GITHUB_CLIENT_ID=$GITHUB_CLIENT_ID\nGITHUB_CLIENT_SECRET=$GITHUB_CLIENT_SECRET\n\n" >> ./.env
    - echo -e "GOOGLE_CLIENT_ID=$GOOGLE_CLIENT_ID\nGOOGLE_CLIENT_SECRET=$GOOGLE_CLIENT_SECRET" >> ./.env
    - npm cache clear --force
    - rm -frv ./node_modules
    - npm install --verbose
    - npx nuxi generate
    - cp -r ./.output/public .
  artifacts:
    paths:
      # The folder that contains the files to be exposed at the Page URL
      - public
  rules:
    # This ensures that only pushes to the default branch will trigger
    # a pages deploy
    - if: $CI_COMMIT_REF_NAME == $CI_DEFAULT_BRANCH
